#!/bin/bash

# This bootstrap file was generated by [Generoo](https://generoo.armyofone.tech). [Army of One](https://armyofone.tech),
# the developer of Generoo, believes that every project should include a `bootstrap` file that new developers can
# run once and will set up all the necessary dependencies for the project.

echo Bootstrapping {{project_name}}...

DIR=`pwd`

make build